version: "3.9"
services:
  collector:
    build: ./collector
    env_file: .env
    depends_on: [db]
  cleaner:
    build: ./cleaner
    env_file: .env
    depends_on: [db]
  scorer:
    build: ./scorer
    env_file: .env
    depends_on: [db]
  dashboard:
    build: ./dashboard
    env_file: .env
    ports:
      - "3000:3000"
    depends_on: [db]
  db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=scoutpg
      - POSTGRES_USER=scout
      - POSTGRES_DB=scoutdb
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
